version: '3'
services:
  jekyll:
    build: 
      context: docker/jekyll
      args:
        uid: "${_UID:-1000}"
        user: "${_USER:-appuser}"
        gid: "${_GID:-1000}"
        group: "${_GROUP:-appgroup}"
    volumes:
      - .:/appdata
    working_dir: /appdata
    ports:
      - "4000:4000"
      - "35729:35729"
    stdin_open: true
    tty: true
    hostname: jekyll.local
    container_name: jekyll.local
    network_mode: "bridge"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M

networks:
  bridge:
    external: true
